import copy from '../copy/copy.json';
import Image from 'next/image';
import { ITestimonialCell } from '../components/types';
import profileImage from '../public/hsilva-tabakalera.jpeg';
import { SocialMediaBar } from '../components/SocialMediaBar';
import { TestimonialCell } from '../components/TestimonialCell';
import styles from '../styles/Home.module.css';

export default function Home() {
    const testimonials = copy?.testimonials;
    return (
        <div className={styles.container}>
            <h1 className={styles.title}>{copy.hanna_silva}</h1>
            <div className={styles.imageContainer}>
                <Image
                    className={styles.image}
                    src={profileImage}
                    alt="Profile picture"
                    sizes="320 640 750"
                    width={512}
                    height={341}
                />
            </div>
            <div className={styles.body}>
                Hannah Silva is a writer and performer working in sound poetry,
                radio, and experimental non-fiction. Their record{' '}
                <em>{copy.talk_in_a_bit}</em> was included in The Wire&apos;s
                Top 25 Albums of 2018. They have written eight plays for BBC
                Radio 3 and 4, and won the Tinniswood Award for best script and
                numerous placements in the BBC Audio Drama Awards. Their debut
                poetry collection <em>{copy.forms_of_protest_title_2}</em> was
                Highly Commended in the Forward Prizes. Their latest radio play{' '}
                <em>{copy.intelligent_guide_title_2}</em> was written using text
                generated by a machine-learning algorithm (Afonica, Radio 4) and
                starred Fiona Shaw. It was the starting point for{' '}
                <em>{copy.my_child_the_algorithm_title}</em>, a memoir about
                queer single parenting and love, forthcoming from Footnote Press
                in 2023. Silva holds a PhD from Stirling University on the
                analysis of poetry and performance, and is currently an
                Leverhulme Early Career Fellow at Queen Mary University, London.
            </div>
            <SocialMediaBar />
            <div className={styles.testimonials}>
                {testimonials?.map(
                    (
                        { quote, footer, stars }: ITestimonialCell,
                        index: number
                    ) => (
                        <TestimonialCell
                            key={index}
                            quote={quote}
                            footer={footer}
                            stars={stars}
                        />
                    )
                )}
            </div>
        </div>
    );
}
